#include "report.hpp"
#include <spdlog/spdlog.h>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;

namespace mqc {

// ============ 默认 HTML 模板 ============

const char* ReportGenerator::DEFAULT_TEMPLATE = R"(<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 20px; }
        .header { background: #f8f9fa; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        .module { margin-bottom: 30px; padding: 20px; border: 1px solid #e9ecef; border-radius: 8px; }
        .module h2 { color: #343a40; margin-top: 0; }
        .plot-container { margin: 20px 0; }
        .general-stats { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .general-stats th, .general-stats td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #dee2e6; }
        .general-stats th { background: #f8f9fa; font-weight: 600; }
        .general-stats tr:hover { background: #f8f9fa; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ title }}</h1>
        {% if report_comment %}<p>{{ report_comment }}</p>{% endif %}
    </div>
    
    {% if has_general_stats %}
    <div class="module">
        <h2>General Statistics</h2>
        {{ general_stats_html }}
    </div>
    {% endif %}
    
    {% for module in modules %}
    <div class="module" id="{{ module.anchor }}">
        <h2>{{ module.name }}</h2>
        <p>{{ module.info }}</p>
        
        {% for section in module.sections %}
        <div class="section">
            <h3>{{ section.name }}</h3>
            <p>{{ section.description }}</p>
            {% if section.content %}{{ section.content }}{% endif %}
            {% if section.plot_id %}
            <div id="plot-{{ section.plot_id }}" class="plot-container"></div>
            <script>
                Plotly.newPlot('plot-{{ section.plot_id }}', {{ section.plot_data }});
            </script>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d;">
        <p>Generated by MultiQC C++</p>
    </footer>
</body>
</html>
)";

// ============ ReportGenerator 实现 ============

ReportGenerator::ReportGenerator(ReportConfig config)
    : config_(std::move(config)) {
    
    // 设置 Inja 模板路径
    if (!config_.template_dir.empty()) {
        env_.set_template_path(config_.template_dir);
    }
}

void ReportGenerator::add_module(const BaseModule& module) {
    modules_.push_back(&module);
    spdlog::debug("Added module to report: {}", module.id());
}

void ReportGenerator::set_template(const fs::path& template_path) {
    template_path_ = template_path;
    if (fs::exists(template_path)) {
        env_.set_template_path(template_path.parent_path().string());
        spdlog::info("Set custom template: {}", template_path.string());
    } else {
        spdlog::warn("Template not found, using default: {}", template_path.string());
    }
}

std::string ReportGenerator::generate(const fs::path& output_dir) {
    spdlog::info("Generating report in: {}", output_dir.string());
    
    // 创建输出目录
    if (config_.make_data_dir) {
        fs::create_directories(output_dir / config_.data_dir);
        write_data_files(output_dir / config_.data_dir);
    }
    
    if (config_.export_plots) {
        fs::create_directories(output_dir / config_.plots_dir);
        write_plot_files(output_dir / config_.plots_dir);
    }
    
    // 准备模板数据
    nlohmann::json data;
    data["title"] = config_.title;
    data["report_comment"] = config_.report_comment;
    data["intro_text"] = config_.intro_text;
    
    // 通用统计表
    data["has_general_stats"] = false;
    data["general_stats_html"] = "";
    
    // 模块数据
    std::vector<nlohmann::json> modules_json;
    for (const auto* module : modules_) {
        nlohmann::json mod_json;
        mod_json["id"] = module->id();
        mod_json["name"] = module->name();
        mod_json["info"] = module->info();
        mod_json["anchor"] = module->anchor_;
        
        // 章节
        mod_json["sections"] = nlohmann::json::array();
        for (const auto& section : module->sections()) {
            nlohmann::json sec_json;
            sec_json["name"] = section.name;
            sec_json["anchor"] = section.anchor;
            sec_json["description"] = section.description;
            
            if (section.content.has_value()) {
                sec_json["content"] = section.content.value();
            }
            
            if (section.plot_id.has_value()) {
                sec_json["plot_id"] = section.plot_id.value();
                // 查找并渲染图表
                for (const auto& plot : module->plots()) {
                    if (plot.config.id == section.plot_id.value()) {
                        sec_json["plot_data"] = render_plotly_config(plot);
                        break;
                    }
                }
            }
            
            mod_json["sections"].push_back(sec_json);
        }
        
        modules_json.push_back(mod_json);
    }
    data["modules"] = modules_json;
    
    // 渲染模板
    std::string html;
    if (fs::exists(template_path_)) {
        auto tmpl = env_.parse_template(template_path_.string());
        html = env_.render(tmpl, data);
    } else {
        // 使用默认模板
        auto tmpl = env_.parse(DEFAULT_TEMPLATE);
        html = env_.render(tmpl, data);
    }
    
    // 写入文件
    auto output_path = output_dir / config_.output_fn;
    std::ofstream ofs(output_path);
    if (!ofs.is_open()) {
        spdlog::error("Failed to write report: {}", output_path.string());
        return "";
    }
    ofs << html;
    ofs.close();
    
    spdlog::info("Report written: {} ({} bytes)", output_path.string(), html.size());
    
    return output_path.string();
}

void ReportGenerator::write_data_files(const fs::path& output_dir) {
    spdlog::info("Writing data files to: {}", output_dir.string());
    
    // 写入通用统计表
    nlohmann::json all_data;
    
    for (const auto* module : modules_) {
        // 每个模块的数据
        const auto& data = module->data();
        if (!data.empty()) {
            all_data[module->id()] = data;
        }
    }
    
    auto data_path = output_dir / "multiqc_data.json";
    std::ofstream ofs(data_path);
    if (ofs.is_open()) {
        ofs << all_data.dump(2);
        ofs.close();
        spdlog::info("Data written: {}", data_path.string());
    }
}

void ReportGenerator::write_plot_files(const fs::path& output_dir) {
    spdlog::info("Writing plot files to: {}", output_dir.string());
    
    for (const auto* module : modules_) {
        for (const auto& plot : module->plots()) {
            auto plot_path = output_dir / (plot.config.id + ".json");
            std::ofstream ofs(plot_path);
            if (ofs.is_open()) {
                auto config = render_plotly_config(plot);
                ofs << config.dump(2);
                ofs.close();
            }
        }
    }
}

std::string ReportGenerator::render_plotly_config(const PlotData& plot) {
    nlohmann::json config;
    
    // 根据图表类型生成配置
    switch (plot.config.type) {
        case PlotType::Bar:
            config = PlotlyGenerator::bar_plot(plot);
            break;
        case PlotType::Line:
            config = PlotlyGenerator::line_plot(plot);
            break;
        case PlotType::Scatter:
            config = PlotlyGenerator::scatter_plot(plot);
            break;
        case PlotType::Heatmap:
            config = PlotlyGenerator::heatmap_plot(plot);
            break;
        default:
            config = PlotlyGenerator::bar_plot(plot);
    }
    
    return config.dump();
}

// ============ PlotlyGenerator 实现 ============

nlohmann::json PlotlyGenerator::bar_plot(const PlotData& plot) {
    nlohmann::json data = nlohmann::json::array();
    
    // 转换数据为 Plotly 格式
    std::vector<std::string> labels;
    std::vector<double> values;
    
    if (plot.data.is_object()) {
        for (auto& [key, value] : plot.data.items()) {
            labels.push_back(key);
            if (value.is_number()) {
                values.push_back(value.get<double>());
            }
        }
    }
    
    nlohmann::json trace;
    trace["type"] = "bar";
    trace["x"] = labels;
    trace["y"] = values;
    trace["name"] = plot.config.title;
    
    data.push_back(trace);
    
    nlohmann::json layout;
    layout["title"] = plot.config.title;
    layout["xaxis"]["title"] = plot.config.xlab;
    layout["yaxis"]["title"] = plot.config.ylab;
    
    return {{"data", data}, {"layout", layout}};
}

nlohmann::json PlotlyGenerator::line_plot(const PlotData& plot) {
    nlohmann::json data = nlohmann::json::array();
    
    nlohmann::json trace;
    trace["type"] = "scatter";
    trace["mode"] = "lines";
    trace["name"] = plot.config.title;
    
    // 简化处理，实际应从 plot.data 提取 x/y
    trace["x"] = nlohmann::json::array();
    trace["y"] = nlohmann::json::array();
    
    if (plot.data.is_object()) {
        for (auto& [key, value] : plot.data.items()) {
            trace["x"].push_back(key);
            if (value.is_number()) {
                trace["y"].push_back(value.get<double>());
            }
        }
    }
    
    data.push_back(trace);
    
    nlohmann::json layout;
    layout["title"] = plot.config.title;
    layout["xaxis"]["title"] = plot.config.xlab;
    layout["yaxis"]["title"] = plot.config.ylab;
    
    return {{"data", data}, {"layout", layout}};
}

nlohmann::json PlotlyGenerator::scatter_plot(const PlotData& plot) {
    nlohmann::json data = nlohmann::json::array();
    
    nlohmann::json trace;
    trace["type"] = "scatter";
    trace["mode"] = "markers";
    trace["name"] = plot.config.title;
    
    // 简化处理
    trace["x"] = nlohmann::json::array();
    trace["y"] = nlohmann::json::array();
    
    data.push_back(trace);
    
    nlohmann::json layout;
    layout["title"] = plot.config.title;
    layout["xaxis"]["title"] = plot.config.xlab;
    layout["yaxis"]["title"] = plot.config.ylab;
    
    return {{"data", data}, {"layout", layout}};
}

nlohmann::json PlotlyGenerator::heatmap_plot(const PlotData& plot) {
    nlohmann::json data = nlohmann::json::array();
    
    nlohmann::json trace;
    trace["type"] = "heatmap";
    trace["name"] = plot.config.title;
    
    // 简化处理，实际应提取 z 矩阵
    trace["z"] = nlohmann::json::array();
    
    data.push_back(trace);
    
    nlohmann::json layout;
    layout["title"] = plot.config.title;
    
    return {{"data", data}, {"layout", layout}};
}

nlohmann::json PlotlyGenerator::multiqc_template() {
    // MultiQC 风格的颜色和字体
    nlohmann::json template_config;
    template_config["colorway"] = {"#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", 
                                   "#9467bd", "#8c564b", "#e377c2", "#7f7f7f"};
    template_config["font"] = {
        {"family", "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto"},
        {"size", 12}
    };
    template_config["paper_bgcolor"] = "rgba(0,0,0,0)";
    template_config["plot_bgcolor"] = "rgba(0,0,0,0)";
    
    return template_config;
}

} // namespace mqc
